version: '3.3'

services:

  # webserver:
  #    image: nginx:alpine
  #    container_name: webserver
  #    tty: true
  #    ports:
  #     - "80:80"
  #     - "443:443"
  #    volumes:
  #     - ./app/conf.d:/etc/nginx/conf.d

  novaincarwp:
    container_name: novaincarwp
    image: wordpress:latest
    ports:
      - 80
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-content:/var/www/html/wp-content
    environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: novaincar_
       WORDPRESS_SITEURL: https://novincar.com
       WORDPRESS_HOME: https://novincar.com
    depends_on:
      - db
    links:
      - db
    networks:
      mynetwork:
        ipv4_address: 172.20.0.6

  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: somewordpress
      UPLOAD_LIMIT: 10000M
    ports:
      - 8080:80
    links:
      - db:db
    networks:
      mynetwork:
        ipv4_address: 172.20.0.5

  db:
    container_name: db
    image: mysql:latest
    ports:
      - 3306:3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    networks:
      mynetwork:
        ipv4_address: 172.20.0.4

volumes:
    db_data: {}

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24
